### ISSUE TITLE
Workspaces -> Delete Workspace -> Check if it was the active one

### ISSUE THREAD

**Issue by pcampanella** [wasdi-cloud/wasdiClient2#60]
The user open a workspace xx
then goes in workspaces
deletes workspace xx
goes in edit

Is handled some how, but you should not be allowed to move. Also the workspace info stay in the box under the workspace list.
We should clean active workspace if the workspace deleted was the active one.

**Comment by pcampanella** [comment]
Much better, but the panel in the workspaces view still is not cleaned.
Here I just deleted the active workspace, edit is disabled as expected, but the info are there inconsistent:


![Image](https://github.com/wasdi-cloud/wasdiClient2/assets/6428249/158f84fc-313e-44fc-be5a-7d8a1b528081)

**Comment by pcampanella** [comment]
Indeed it looks also there that a language code is missing (WORKSPACES_NAME) should be some translation problem

**Comment by pcampanella** [comment]
I do not see this solved. If it is not clear contact me.

**Comment by bspurgeon08** [comment]
@pcampanella for some reason the behaviour was different in test vs in prod (in test, the fields were cleared and the WORKSPACES_NAME appeared as name) - I rebuilt the client in prod and it seems to me to be fixed now

![Image](https://github.com/wasdi-cloud/wasdiClient2/assets/109524059/65f4559d-33e3-4311-ab93-06cd71513e28)



![Image](https://github.com/wasdi-cloud/wasdiClient2/assets/109524059/e015618b-4624-4543-9e55-52064c8863be)

**Comment by kr1zz** [comment]
Not sure if it's related, but I tried deleting a workspace and after the confirmation request, nothing happened. I think this is partially due to the backend taking some time, but I opened WASDI (old client) with another account I previously shared the workspace with, and could still see it. Then, I opened another workspace with the first account in the new client, and then went back to workspaces, and it was finally gone
